const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  startHarness: () => ipcRenderer.invoke('harness:start'),
  stopHarness: () => ipcRenderer.invoke('harness:stop'),
  getStatus: () => ipcRenderer.invoke('harness:status'),
  getLogs: () => ipcRenderer.invoke('harness:logs'),
  openWeb: () => ipcRenderer.invoke('harness:openWeb'),
  listResults: () => ipcRenderer.invoke('results:list'),
  getUsageStats: () => ipcRenderer.invoke('stats:usage'),
  ghStatus: () => ipcRenderer.invoke('github:status'),
  ghDetectKeys: () => ipcRenderer.invoke('github:detectKeys'),
  ghPickKey: () => ipcRenderer.invoke('github:pickKey'),
  ghConnect: (opts) => ipcRenderer.invoke('github:connect', opts),
  ghOpenKeysPage: () => ipcRenderer.invoke('github:openKeysPage'),
  ghLogout: () => ipcRenderer.invoke('github:logout'),
  ghRepos: () => ipcRenderer.invoke('github:repos'),
  ghAddRepo: (input) => ipcRenderer.invoke('github:addRepo', input),
  ghRemoveRepo: (url) => ipcRenderer.invoke('github:removeRepo', url),
  ghListTokenStatus: () => ipcRenderer.invoke('github:listTokenStatus'),
  ghSetListToken: (token) => ipcRenderer.invoke('github:setListToken', token),
  ghClearListToken: () => ipcRenderer.invoke('github:clearListToken'),
  ghBranches: (url) => ipcRenderer.invoke('github:branches', { url }),
  ghTree: (url, branch) => ipcRenderer.invoke('github:tree', { url, branch }),
  mcpList: () => ipcRenderer.invoke('mcp:list'),
  skillsList: (sessionId) => ipcRenderer.invoke('skills:list', sessionId),
  onLog: (cb) => ipcRenderer.on('harness:log', (_e, lines) => cb(lines)),
  onState: (cb) => ipcRenderer.on('harness:state', (_e, state) => cb(state)),
  chatConnect: () => ipcRenderer.invoke('chat:connect'),
  chatDisconnect: () => ipcRenderer.invoke('chat:disconnect'),
  chatList: () => ipcRenderer.invoke('chat:list'),
  chatCreate: (opts) => ipcRenderer.invoke('chat:create', opts || null),
  chatWorkspaces: () => ipcRenderer.invoke('chat:workspaces'),
  pickWorkspaceDir: () => ipcRenderer.invoke('chat:pickWorkspaceDir'),
  addWorkspace: (path) => ipcRenderer.invoke('chat:addWorkspace', path),
  chatArchiveSession: (sessionId) => ipcRenderer.invoke('chat:archiveSession', sessionId),
  chatHistory: (sessionId) => ipcRenderer.invoke('chat:history', sessionId),
  chatSend: (sessionId, text, images, files, mode) => {
    const content = [];
    if (text) content.push({ type: 'text', text });
    for (const img of images || []) {
      content.push({ type: 'image', mediaType: img.mediaType, data: img.data, name: img.name });
    }
    return ipcRenderer.invoke('chat:send', { sessionId, content, files: files || [], mode: mode || 'queue' });
  },
  pickFiles: () => ipcRenderer.invoke('chat:pickFiles'),
  chatAnswerQuestion: (rpcId, sessionId, answers) =>
    ipcRenderer.invoke('chat:answerQuestion', { rpcId, sessionId, answers }),
  answerApproval: (rpcId, sessionId, approvalId, outcome) =>
    ipcRenderer.invoke('chat:answerApproval', { rpcId, sessionId, approvalId, outcome }),
  marketGet: (path) => ipcRenderer.invoke('market:get', path),
  marketPost: (path, body) => ipcRenderer.invoke('market:post', { path, body }),
  marketBackup: () => ipcRenderer.invoke('market:backup'),
  marketPickBackup: () => ipcRenderer.invoke('market:pickBackup'),
  marketLogExport: () => ipcRenderer.invoke('market:logExport'),
  relaunchApp: () => ipcRenderer.invoke('app:relaunch'),
  chatAttachment: (sessionId, attachmentId) =>
    ipcRenderer.invoke('chat:attachment', { sessionId, attachmentId }),
  chatCancel: (sessionId) => ipcRenderer.invoke('chat:cancel', sessionId),
  chatModels: (sessionId) => ipcRenderer.invoke('chat:models', sessionId),
  chatSelectModel: (sessionId, provider, model, reasoningEffort) =>
    ipcRenderer.invoke('chat:selectModel', { sessionId, provider, model, reasoningEffort }),
  chatPermissionSet: (sessionId, preset) => ipcRenderer.invoke('chat:permissionSet', { sessionId, preset }),
  getPresets: () => ipcRenderer.invoke('settings:presets'),
  readPreset: (agentPreset) => ipcRenderer.invoke('settings:presetRead', agentPreset),
  openPresetDoc: (agentPreset) => ipcRenderer.invoke('settings:presetOpen', agentPreset),
  selectPreset: (sessionId, agentPreset) => ipcRenderer.invoke('settings:presetSelect', { sessionId, agentPreset }),
  getLlmProviders: () => ipcRenderer.invoke('settings:llmProviders'),
  getLlmModels: () => ipcRenderer.invoke('settings:llmModels'),
  describeCredentials: (refs) => ipcRenderer.invoke('credentials:describe', refs),
  setCredential: (ref, value) => ipcRenderer.invoke('credentials:set', { ref, value }),
  unsetCredential: (ref) => ipcRenderer.invoke('credentials:unset', ref),
  mutateSettings: (ns, ops, expectedRevision) => ipcRenderer.invoke('settings:mutate', { ns, ops, expectedRevision }),
  discoverModels: (settingsNs, provider, apiKey) => ipcRenderer.invoke('llm:discoverModels', { settingsNs, provider, apiKey }),
  getSettingsDescribe: () => ipcRenderer.invoke('settings:describe'),
  getPluginCatalog: () => ipcRenderer.invoke('settings:pluginCatalog'),
  getPresetDefault: () => ipcRenderer.invoke('settings:presetDefault'),
  setPresetDefault: (preset) => ipcRenderer.invoke('settings:setPresetDefault', preset),
  openSettingsDoc: () => ipcRenderer.invoke('settings:openDoc'),
  onChatFrame: (cb) => ipcRenderer.on('chat:frame', (_e, msg) => cb(msg)),
  checkUpdate: () => ipcRenderer.invoke('updater:check'),
  downloadUpdate: (url) => ipcRenderer.invoke('updater:download', url),
  onUpdaterProgress: (cb) => ipcRenderer.on('updater:progress', (_e, p) => cb(p)),
  onUpdaterResult: (cb) => ipcRenderer.on('updater:result', (_e, p) => cb(p)),
  getApiKey: () => ipcRenderer.invoke('settings:getApiKey'),
  setApiKey: (key) => ipcRenderer.invoke('settings:setApiKey', key),
});
